import SiteHeader from "@/app/components/SiteHeader";

export default function Page(){return <main className="servicePage legalSitePage"><SiteHeader/><section className="legalHero"><div><p className="hand">VERSHNYK Handwerk & Montage</p><h1>DATENSCHUTZ</h1></div></section><section className="legalPage"><div className="legalWrap">
<section><h2>1. Verantwortlicher</h2><p>Verantwortlich für die Datenverarbeitung auf dieser Website ist:<br/><strong>Maksym Chyrka · VERSHNYK – Handwerk & Montage</strong><br/>Neue Priel 22 · 87700 Memmingen · Deutschland<br/>E-Mail: <a href="mailto:info@vershnyk.com">info@vershnyk.com</a></p></section>
<section><h2>2. Allgemeine Hinweise</h2><p>Personenbezogene Daten werden nur verarbeitet, soweit dies für den Betrieb dieser Website, die Bearbeitung von Anfragen, die Vertragsanbahnung oder die Erfüllung gesetzlicher Pflichten erforderlich ist. Rechtsgrundlagen sind insbesondere Art. 6 Abs. 1 lit. b, c und f DSGVO.</p></section>
<section><h2>3. Hosting über Vercel</h2><p>Diese Website wird über Vercel bereitgestellt. Beim Aufruf können technisch erforderliche Verbindungs- und Protokolldaten wie IP-Adresse, Zeitpunkt, aufgerufene Ressource sowie Browser- und Geräteinformationen verarbeitet werden. Dies erfolgt zur sicheren und zuverlässigen Bereitstellung der Website auf Grundlage unseres berechtigten Interesses gemäß Art. 6 Abs. 1 lit. f DSGVO. Bei einer Verarbeitung außerhalb des EWR gelten die hierfür vorgesehenen gesetzlichen Übermittlungsmechanismen.</p></section>
<section><h2>4. Kontakt über WhatsApp</h2><p>Bei einer Kontaktaufnahme über WhatsApp verarbeiten wir die von Ihnen übermittelten Angaben, insbesondere Kontaktdaten, Nachrichten, Fotos und gegebenenfalls die zur Einschätzung des Auftrags mitgeteilte Adresse. Die Verarbeitung erfolgt zur Bearbeitung Ihrer Anfrage und zur Vertragsanbahnung gemäß Art. 6 Abs. 1 lit. b DSGVO. WhatsApp ist ein externer Dienst; für dessen eigene Datenverarbeitung gelten zusätzlich die Datenschutzbestimmungen des Anbieters.</p></section>
<section><h2>5. Anfrage und Angebot</h2><p>Eine Kontaktaufnahme über WhatsApp oder die Anzeige eines freien Kalendertages stellt keine verbindliche Buchung dar. Nach Klärung von Umfang und Termin kann ein individuelles Angebot übermittelt werden. Daten aus Anfragen und Angeboten werden nur so lange gespeichert, wie dies für die Bearbeitung, Vertragsabwicklung oder gesetzliche Aufbewahrungspflichten erforderlich ist.</p></section>
<section><h2>6. Google-Bewertungen</h2><p>Auf dieser Website werden öffentlich zugängliche Google-Bewertungen über eine serverseitige Schnittstelle abgerufen und dargestellt. Dabei können Name, Bewertung, Bewertungstext, Datum und öffentlich verfügbare Profildaten des Verfassers angezeigt werden. Beim bloßen Besuch unserer Website wird die Google-Bewertungsseite nicht automatisch im Browser geöffnet. Erst beim Anklicken eines Google-Links verlassen Sie unsere Website und es gelten die Datenschutzbestimmungen von Google.</p></section>
<section><h2>7. Instagram</h2><p>Öffentliche Inhalte unseres Instagram-Auftritts, darunter Medien, Bildunterschriften, Links und die Anzahl der Follower, können serverseitig über die Instagram-Schnittstelle abgerufen und auf dieser Website angezeigt werden. Beim bloßen Seitenaufruf wird dadurch keine Instagram-Seite im Browser des Besuchers geöffnet. Beim Anklicken eines Instagram-Links gelten die Datenschutzbestimmungen des jeweiligen Plattformanbieters.</p></section>
<section><h2>8. YouTube</h2><p>Informationen zu unserem YouTube-Kanal, Videos und Shorts, insbesondere Titel, Vorschaubilder, Links und öffentlich verfügbare Kanalinformationen, werden serverseitig abgerufen und auf der Website dargestellt. Es werden auf dieser Website keine YouTube-Videoplayer automatisch eingebettet. Erst beim Anklicken eines Links wird YouTube aufgerufen; ab diesem Zeitpunkt gelten die Datenschutzbestimmungen des Plattformanbieters.</p></section>
<section><h2>9. Google Kalender</h2><p>Zur Anzeige unserer Verfügbarkeit wird ein Kalender serverseitig ausgewertet. An den Browser werden ausschließlich belegte bzw. freie Kalendertage übermittelt. Namen, Adressen, Titel oder sonstige Inhalte unserer Kalendereinträge werden nicht öffentlich ausgegeben. Die Anzeige dient ausschließlich der unverbindlichen Terminorientierung; eine Buchung erfolgt erst nach individueller Bestätigung.</p></section>
<section><h2>10. Externe Links</h2><p>Unsere Website enthält Links zu externen Diensten wie WhatsApp, Google, Instagram und YouTube. Daten werden durch das Anklicken solcher Links an den jeweiligen Anbieter übermittelt. Auf Art und Umfang der dortigen Verarbeitung haben wir keinen Einfluss.</p></section>
<section><h2>11. Speicherdauer</h2><p>Personenbezogene Daten werden nur so lange gespeichert, wie dies für den jeweiligen Zweck erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen. Nach Wegfall des Zwecks und Ablauf gesetzlicher Fristen werden die Daten gelöscht.</p></section>
<section><h2>12. Ihre Rechte</h2><p>Sie haben im Rahmen der gesetzlichen Voraussetzungen insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung kann mit Wirkung für die Zukunft widerrufen werden. Außerdem besteht ein Beschwerderecht bei einer zuständigen Datenschutzaufsichtsbehörde.</p></section>
<section><h2>13. SSL-/TLS-Verschlüsselung</h2><p>Diese Website nutzt eine verschlüsselte Verbindung, um übertragene Daten gegen unbefugten Zugriff zu schützen.</p></section>
<section><h2>14. Aktualität</h2><p>Diese Datenschutzerklärung wird angepasst, wenn sich Funktionen, eingesetzte Dienste oder rechtliche Anforderungen ändern.</p></section>
<p className="legalNote">Stand: Oktober 2026</p></div></section><footer className="detailFooter"><div><strong>VERSHNYK</strong><small>HANDWERK & MONTAGE</small></div><p>IDEEN. MONTAGE. ERGEBNISSE.</p><nav><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a><a href="/">Startseite</a></nav></footer></main>}