"use client";
import {site} from "@/data/site";
import {logo} from "@/data/logo";
const hero="https://aimbestmowing.com/_next/image?q=75&url=%2Fhedge-trimming-wide.png&w=3840";
export default function Gartenpflege(){
 const items=["Rasen mähen & pflegen","Hecken schneiden","Baum- und Strauchschnitt","Beete und Gartenflächen pflegen","Saisonale Gartenarbeiten","Aufräum- und Rückschnittarbeiten"];
 return <main className="servicePage">
  <header className="detailHeader"><a className="brand" href="#start"><img src={logo} alt="VERSHNYK"/><span><strong>VERSHNYK</strong><small>HANDWERK & MONTAGE</small></span></a><a className="homeLink" href="/">← Startseite</a><div className="actions"><a className="ig" href={site.instagram} aria-label="Instagram"><svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1"/></svg></a><a className="yt" href={site.youtube} aria-label="YouTube"><svg viewBox="0 0 24 24"><path d="M3.5 7.2A3.5 3.5 0 0 1 6 4.7c4-.5 8-.5 12 0a3.5 3.5 0 0 1 2.5 2.5c.5 3.2.5 6.4 0 9.6a3.5 3.5 0 0 1-2.5 2.5c-4 .5-8 .5-12 0a3.5 3.5 0 0 1-2.5-2.5 31 31 0 0 1 0-9.6Z"/><path className="play" d="m10 9 5 3-5 3Z"/></svg></a><a className="wicon" href={site.whatsapp} aria-label="WhatsApp"><svg viewBox="0 0 24 24"><path d="M20 11.7a8 8 0 0 1-11.8 7l-4.2 1.1 1.1-4A8 8 0 1 1 20 11.7Z"/><path d="M8.2 7.8c.4-.4.8-.2 1 .2l.8 1.8c.1.3 0 .6-.2.8l-.6.7c.8 1.6 2 2.8 3.7 3.5l.7-.8c.2-.2.5-.3.8-.2l1.8.8c.4.2.5.6.3 1-.5.9-1.4 1.5-2.4 1.4-3.7-.4-7.2-3.8-7.5-7.5-.1-.7.2-1.3.6-1.7Z"/></svg></a><a className="whatsapp" href={site.whatsapp}>◉ &nbsp; Anfrage über WhatsApp&nbsp; →</a></div></header>
  <section className="detailHero" style={{backgroundImage:`url("${hero}")`}}><div className="detailOverlay"><p className="hand">Haus & Garten</p><h1>GARTENPFLEGE.</h1><p>Zuverlässige Gartenpflege für private Grundstücke – sauber, direkt und unkompliziert.</p><div className="detailHeroBottom"><div className="servicePrice"><b>48 €</b><span>pro Stunde<small>zzgl. Fahrtkosten</small></span></div><a className="detailWa" href={site.whatsapp}>Projekt über WhatsApp senden →</a></div></div></section>
  <section className="serviceIntro"><div><p className="hand">Was ich für Sie mache</p><h2>PFLEGE, DIE MAN SIEHT.</h2><p>Von regelmäßiger Pflege bis zum einmaligen Rückschnitt: Sie senden mir kurz, was gemacht werden soll, idealerweise mit Fotos. Danach klären wir Umfang und Termin direkt über WhatsApp.</p></div><div className="serviceFacts"><b>48 € / Std.</b><span>+ Fahrtkosten</span><b>WhatsApp</b><span>direkte Abstimmung</span><b>Termin wählen</b><span>freie Termine im Kalender ansehen</span></div></section>
  <section className="serviceList"><p className="hand">Leistungen</p><h2>GARTENPFLEGE IM ÜBERBLICK</h2><div>{items.map((x,i)=><article key={x}><b>0{i+1}</b><span>{x}</span></article>)}</div></section>
  <section className="serviceGallery"><div style={{backgroundImage:`url("${hero}")`}}></div><div className="galleryCopy"><p className="hand">Einfach anfragen</p><h2>FOTOS SENDEN.<br/>AUFWAND KLÄREN.<br/><span>TERMIN FINDEN.</span></h2><p>Schicken Sie Fotos, Adresse und eine kurze Beschreibung. So kann ich den Aufwand vorab besser einschätzen.</p><a className="heroWa" href={site.whatsapp}>Jetzt über WhatsApp anfragen →</a></div></section>
  <section className="serviceBottom"><div><b>⌖</b><h3>EINSATZGEBIET</h3><p>Rund um Memmingen / Allgäu, in der Regel bis 200 km. Weiter auf Anfrage.</p></div><div><b>▦</b><h3>TERMIN</h3><p>Verfügbarkeit ansehen, Termin nach Bestätigung.</p></div><div><b>◉</b><h3>WHATSAPP</h3><p>Fotos und Projektdetails direkt senden.</p></div></section>
 <footer className="detailFooter"><div><strong>VERSHNYK</strong><small>HANDWERK & MONTAGE</small></div><p>© 2026 VERSHNYK · Handwerk & Montage</p><nav><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a><a href="/">Startseite</a></nav></footer></main>
}